# Baseado em Python 3.10 slim
FROM python:3.10-slim

# Define o diretório de trabalho
WORKDIR /app

# Copia o arquivo de dependências e instala as dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo o código do serviço para o container
COPY . .

# Expõe a porta 5001 do container
EXPOSE 5001

# Define o entrypoint para executar o serviço
ENTRYPOINT ["python", "run.py"]
